
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/team03-s23-6pm-1
owner: ucsb-cs156-s23
repo_name: team03-s23-6pm-1
pull_requests: [{"author":{"id":"U_kgDOBX6DSQ","is_bot":false,"login":"mfletcher2","name":"Max Fletcher"},"headRefName":"Max-BookFrontend2Backend","number":23,"title":"Convert Book frontend to use Backend","url":"https://github.com/ucsb-cs156-s23/team03-s23-6pm-1/pull/23"},{"author":{"id":"MDQ6VXNlcjI0MjM3MDY1","is_bot":false,"login":"GlassBricks","name":"Benjamin Ye"},"headRefName":"ben-restaurant-convert-frontend","number":19,"title":"Convert restaurant frontend to use backend","url":"https://github.com/ucsb-cs156-s23/team03-s23-6pm-1/pull/19"}]
