
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/team03-s23-6pm-1
owner: ucsb-cs156-s23
repo_name: team03-s23-6pm-1
pull_requests: [{"author":{"id":"U_kgDOBXzGpA","is_bot":false,"login":"albertyu03","name":"Albert Yu"},"headRefName":"Albert-BookBackend","number":18,"title":"Add backend CRUD for Book from team02","url":"https://github.com/ucsb-cs156-s23/team03-s23-6pm-1/pull/18"},{"author":{"id":"MDQ6VXNlcjI0MjM3MDY1","is_bot":false,"login":"GlassBricks","name":"Benjamin Ye"},"headRefName":"ben-restaurant-backend","number":15,"title":"Bring over restaurant backend files from team02","url":"https://github.com/ucsb-cs156-s23/team03-s23-6pm-1/pull/15"},{"author":{"id":"U_kgDOBX6DSQ","is_bot":false,"login":"mfletcher2","name":"Max Fletcher"},"headRefName":"max-restaurantfrontend","number":14,"title":"Add frontend crud files for Restaurant from team01 ","url":"https://github.com/ucsb-cs156-s23/team03-s23-6pm-1/pull/14"},{"author":{"id":"MDQ6VXNlcjQzOTgwMDA5","is_bot":false,"login":"TheRealJBomb","name":"Jake G"},"headRefName":"jake-bring-over-frontend-crud-files-for-hotel-from-team01","number":13,"title":"add frontend crud files for hotel from team01","url":"https://github.com/ucsb-cs156-s23/team03-s23-6pm-1/pull/13"}]
